/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import dao.KullaniciDao;
import entity.Kullanici;
import javax.swing.JOptionPane;

/**
 *
 * @author m07er
 */
public class KullaniciKayitPanel extends javax.swing.JFrame {

    /**
     * Creates new form KullaniciKayitPanel
     */
    KullaniciDao kullaniciDao = new KullaniciDao();
    Kullanici kullanici = new Kullanici();

    public KullaniciKayitPanel() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    void kayit() {

        String adi = adtf.getText();
        String email = emailtf.getText();
        String sifre = sifretf.getText();
        String telno = telnotf.getText();

        boolean emailKontrol = false;
        boolean telnoKontrol = false;
        
        if (adi.equalsIgnoreCase("") || email.equalsIgnoreCase("") || sifre.equalsIgnoreCase("") || telno.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(rootPane, "Lütfen boş alanları doldurunuz!");
        } else {
            for (int i = 0; i < this.kullaniciDao.list().size(); i++) {
                if (email.equalsIgnoreCase(this.kullaniciDao.list().get(i).getKullanici_email())) {
                    emailKontrol = true;
                }
                if (telno.equalsIgnoreCase(this.kullaniciDao.list().get(i).getKullanici_telno())) {
                    telnoKontrol = true;
                }
            }

            if (emailKontrol && telnoKontrol) {
                JOptionPane.showMessageDialog(rootPane, "Bu email ve telefon numarası için bir kullanici zaten mevcut. Lütfen faklı bir email ve telefon numarası ile deneyiniz!");
            } else if (telnoKontrol) {
                JOptionPane.showMessageDialog(rootPane, "Bu telefon numarası için bir kullanici zaten mevcut. Lütfen faklı bir telefon numarası ile deneyiniz!");
            } else if (emailKontrol) {
                JOptionPane.showMessageDialog(rootPane, "Bu email için bir kullanici zaten mevcut. Lütfen faklı bir email ile deneyiniz!");
            } else {

                this.kullanici.setKullanici_adi(adi);
                this.kullanici.setKullanici_email(email);
                this.kullanici.setKullanici_sifre(sifre);
                this.kullanici.setKullanici_telno(telno);
                this.kullaniciDao.createKullanici(kullanici);

                for (int i = 0; i < this.kullaniciDao.list().size(); i++) {
                    if (emailtf.getText().equalsIgnoreCase(this.kullaniciDao.list().get(i).getKullanici_email())) {
                        JOptionPane.showMessageDialog(rootPane, "Başarıyla kaydoldunuz.");
                    }
                }
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sifretf = new javax.swing.JPasswordField();
        emailtf = new javax.swing.JTextField();
        adtf = new javax.swing.JTextField();
        telnotf = new javax.swing.JTextField();
        kayıtButton = new javax.swing.JButton();
        vazgecButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Adı Soyadı");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Email");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Şifre");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Telefon Numarası");

        kayıtButton.setText("Kayıt Ol");
        kayıtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayıtButtonActionPerformed(evt);
            }
        });

        vazgecButton.setText("Vazgeç");
        vazgecButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vazgecButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vazgecButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kayıtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(emailtf, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telnotf, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sifretf, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adtf, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(adtf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(emailtf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sifretf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(telnotf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kayıtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vazgecButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vazgecButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vazgecButtonActionPerformed
        // TODO add your handling code here:
        GirisPanel girisPanel = new GirisPanel();
        girisPanel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_vazgecButtonActionPerformed

    private void kayıtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayıtButtonActionPerformed
        // TODO add your handling code here:
        kayit();
    }//GEN-LAST:event_kayıtButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullaniciKayitPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullaniciKayitPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullaniciKayitPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullaniciKayitPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KullaniciKayitPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adtf;
    private javax.swing.JTextField emailtf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton kayıtButton;
    private javax.swing.JPasswordField sifretf;
    private javax.swing.JTextField telnotf;
    private javax.swing.JButton vazgecButton;
    // End of variables declaration//GEN-END:variables
}
