/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import dao.EmlakDao;
import entity.Emlak;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author m07er
 */
public class RaporPanel extends javax.swing.JFrame {

    /**
     * Creates new form Rapor
     */
    EmlakDao emlakDao = new EmlakDao();
    ArrayList<String> kontrol;
    ArrayList<Emlak> emlakList;
    DefaultTableModel tablo = new DefaultTableModel();

    public RaporPanel() {
        initComponents();
        this.setLocationRelativeTo(null);
        emlakRaporVeri();
    }

    void emlakRaporVeri() {
        //combobox veri çekme
        kontrol = new ArrayList<>();
        for (int i = 0; i < emlakDao.list().size(); i++) {
            String tmp = emlakDao.list().get(i).getEmlak_odasayisi();
            if (kontrol.size() >= 1) {
                boolean k = false;
                for (int j = 0; j < kontrol.size(); j++) {
                    String get = kontrol.get(j);
                    if (get.equals(tmp)) {
                        k = true;
                        break;
                    }
                }
                if (!k) {
                    kontrol.add(tmp);
                    odaSayısıCombobox.addItem(tmp);
                }
            } else {
                kontrol.add(tmp);
                odaSayısıCombobox.addItem(tmp);
            }
        }
    }
    
    public String odaSayisi(){
        
        String oda = null;
        for (int i = 0; i < emlakDao.list().size(); i++) {
            if (emlakDao.list().get(i).getEmlak_odasayisi().contains((CharSequence) odaSayısıCombobox.getSelectedItem())) {
                oda = emlakDao.list().get(i).getEmlak_odasayisi();
            }
        }
        return oda;
    }

    void toplam() {

        String oda = odaSayisi();
        int oda_count = 0;

        oda_count = emlakDao.EmlakOdaSayisi(oda);
        odaToplamLabel.setText(String.valueOf(oda_count));
    }

    void listele() {

        String oda = odaSayisi();

        this.tablo = (DefaultTableModel) emlakRaporListe.getModel();
        this.tablo.setRowCount(0);
        Object[] row = new Object[8];
        for (int i = 0; i < emlakDao.list1(oda).size(); i++) {
            row[0] = emlakDao.list1(oda).get(i).getEmlak_id();
            row[1] = emlakDao.list1(oda).get(i).getEmlak_m2();
            row[2] = emlakDao.list1(oda).get(i).getEmlak_odasayisi();
            row[3] = emlakDao.list1(oda).get(i).getEmlak_adres();
            row[4] = emlakDao.list1(oda).get(i).getEmlak_isitma();
            row[5] = emlakDao.list1(oda).get(i).getEmlak_aidat();
            row[6] = emlakDao.list1(oda).get(i).getEmlak_esyali();
            row[7] = emlakDao.list1(oda).get(i).getEmlak_fiyat();

            tablo.addRow(row);
        }

        emlakRaporListe.setModel(tablo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        emlakRaporListe = new javax.swing.JTable();
        odaSayısıCombobox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        odaToplamLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        emlakRaporListe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emlak ID", "m2", "Oda Sayısı", "Adres", "Isıtma", "Aidat", "Eşyalı", "Fiyat"
            }
        ));
        emlakRaporListe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emlakRaporListeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(emlakRaporListe);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton1.setText("ARA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Geri dönmek için tıklayınız.");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Toplam : ");

        odaToplamLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(odaSayısıCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(odaToplamLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 461, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(jScrollPane1)
                    .addGap(11, 11, 11)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(odaToplamLabel))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                .addComponent(odaSayısıCombobox, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(485, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(115, 115, 115)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emlakRaporListeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emlakRaporListeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_emlakRaporListeMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        IslemPanel sp = new IslemPanel();
        sp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        toplam();
        listele();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RaporPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RaporPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RaporPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RaporPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RaporPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable emlakRaporListe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> odaSayısıCombobox;
    private javax.swing.JLabel odaToplamLabel;
    // End of variables declaration//GEN-END:variables
}
